# Generated by Django 3.2.22 on 2023-10-27 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20231027_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'GPT Usage',
                'verbose_name_plural': 'GPT Usages',
            },
        ),
    ]
