# Generated by Django 3.2.22 on 2023-10-28 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_user_study_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='participants',
            field=models.ManyToManyField(related_name='quizzes_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=django_jsonform.models.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
