# Generated by Django 3.2.22 on 2023-10-28 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20231028_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='quizzes_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
