# Generated by Django 3.2.22 on 2023-10-28 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_quiz_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
