# Generated by Django 3.2.22 on 2023-10-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_quiz_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxwmlnoJbzLcou6rVQAZ1_ayDmxTKBUs4WaXJ7RmVkZg&s'),
        ),
    ]
